runtime: python39
instance_class: F4
entrypoint: gunicorn -b :$PORT model:app
timeout: 300s

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 20

network: 
  instance_tag: allow-traffic
  forwarded_ports:
    - 8080/tcp

env_variables:
  # Put any required environment variables here

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
