runtime: python39
version: v2
instance_class: F4_1G
entrypoint: gunicorn -b :$PORT model:app

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 20

network: 
  instance_tag: allow-traffic
  forwarded_ports:
    - 8080/tcp

env_variables:
  # Put any required environment variables here

handlers:
- url: /static
  static_dir: build/static
- url: /.*
  script: auto
