runtime: python39
entrypoint: gunicorn -b :$PORT model:app
timeout: 300s
env: flex

resources:
  cpu: 1
  memory_gb: 16
  disk_size_gb: 20


automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 20

network: 
  instance_tag: allow-traffic
  forwarded_ports:
    - 8080/tcp

env_variables:
  # Put any required environment variables here

handlers:
- url: /static
  static_dir: static/
- url: /.*
  script: auto
